Fix `proc macro panicked` with `Invalid type` in `const_random!` in Rust 1.77.
tkaitchuck/constrandom pull request #33
Opened 2024-01-26 03:14 UTC by nnethercote

This PR fixes a compile-time panic with `const_random!` on byte arrays in Rust 1.77. Full details are in the individual commit logs.

2024-01-26 03:24 UTC, dtolnay requested changes
I believe the `usize`/`isize` change is not correct, because it assumes the host's pointer size is at least as large as the target's pointer size. If usize is 4 bytes on the host and 8 bytes on the target, const_random would be producing random usizes that are half zero.

2024-01-26 04:18 UTC, nnethercote commented
Well spotted, thanks. I have updated to remove the first commit changing `usize`/`isize` handling. I also added a comment explaining the subtlety, so nobody else makes the same mistake in the future.

2024-01-26 04:33 UTC, dtolnay commented on macro/src/lib.rs
> +                    // (on the target) and then truncate it to usize (on the host).
```suggestion
                    // be bad. Instead we produce code that will generate a 128-bit integer literal
                    // (on the host) and then truncate it to usize (on the target).
```

2024-01-26 04:41 UTC, nnethercote commented on macro/src/lib.rs
> +                    // (on the target) and then truncate it to usize (on the host).
Fixed, thanks.

2024-01-26 04:48 UTC, dtolnay approved these changes
Thank you! This looks good to me.

2024-01-31 05:51 UTC, nnethercote commented
Oh, this problem may also occur in Rust 1.76.

2024-03-03 22:10 UTC, tkaitchuck approved these changes

2024-03-03 22:11 UTC, merged

2024-03-05 12:59 UTC, decathorpe commented
Would it be possible to get a new version of const-random-macros released with this fix?